///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace tag_case
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the tag_caseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d3f9b2de-809d-4b04-9f6e-3c2b471093fa")]
    public partial class tag_caseRepository : RepoGenBaseFolder
    {
        static tag_caseRepository instance = new tag_caseRepository();
        tag_caseRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the tag_caseRepository element repository.
        /// </summary>
        [RepositoryFolder("d3f9b2de-809d-4b04-9f6e-3c2b471093fa")]
        public static tag_caseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public tag_caseRepository() 
            : base("tag_caseRepository", "/", null, 0, false, "d3f9b2de-809d-4b04-9f6e-3c2b471093fa", ".\\RepositoryImages\\tag_caseRepositoryd3f9b2de.rximgres")
        {
            _rxmainframe = new tag_caseRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d3f9b2de-809d-4b04-9f6e-3c2b471093fa")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("797b59b6-9421-44d3-9203-11c466d84d9d")]
        public virtual tag_caseRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class tag_caseRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("797b59b6-9421-44d3-9203-11c466d84d9d")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "797b59b6-9421-44d3-9203-11c466d84d9d", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "element[@controlname='RxTabcontrol']//text[@accessiblerole='Text']", ".//text[@accessiblerole='Text']", 30000, null, "e36243fa-ced7-4b28-bd48-6504b67151e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("797b59b6-9421-44d3-9203-11c466d84d9d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("797b59b6-9421-44d3-9203-11c466d84d9d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("e36243fa-ced7-4b28-bd48-6504b67151e5")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("e36243fa-ced7-4b28-bd48-6504b67151e5")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
